2021-09-09 15:51:39,784 NEW ROBOT EXUECUTION PROCESS
2021-09-09 15:51:39,784 BASE DIR: /home/pavlicseka/ffm_web
2021-09-09 15:51:39,784 Creating oanda instance
2021-09-09 15:51:39,785 ACCESS TOKEN: acc56198776d1ce7917137567b23f9a1-c5f7a43c7c6ef8563d0ebdd4a3b496ac
2021-09-09 15:51:39,785 ACCOUNT ID: 001-004-2840244-004
2021-09-09 15:51:39,785 ENV: live
2021-09-09 15:51:39,785 SECURITY: EUR_USD
2021-09-09 15:51:39,801 setting up API-client for environment live
2021-09-09 15:51:39,802 performing request https://stream-fxtrade.oanda.com/v3/accounts/001-004-2840244-004/pricing/stream
2021-09-09 15:51:40,691 Internal Server Error: /test/
Traceback (most recent call last):
  File "/home/pavlicseka/python/ffm_web/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/pavlicseka/python/ffm_web/lib/python3.6/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/pavlicseka/ffm_web/mysite/views.py", line 261, in test
    a = run_robot("EUR_USD_TRD1")
  File "/home/pavlicseka/ffm_web/robots/processes/processes.py", line 70, in run_robot
    robot_status = Robots.object.get(name=robot)
AttributeError: type object 'Robots' has no attribute 'object'
2021-09-09 15:52:08,817 /home/pavlicseka/ffm_web/robots/processes/processes.py changed, reloading.
